services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "8000:8000"  # Gunicorn (WSGI)
      - "8001:8001"  # Daphne (ASGI)
    volumes:
      - .:/ai_lang_master
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - CHANNEL_LAYERS=default.layers.channels_redis.RedisChannelLayer
    depends_on:
      - db
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    command: npm start
    stdin_open: true
    tty: true
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=ai_lang_master
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
